name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar proyecto
        run: dotnet build MaquinaCafeTDD.sln --no-restore --configuration Release

      - name: Ejecutar pruebas
        run: dotnet test MaquinaCafeTDD.sln --no-build --configuration Release